const images = {
  header1: require("../server/assets/headers/header1.png"),
  header2: require("../server/assets/headers/header2.png"),
  header3: require("../server/assets/headers/header3.png"),
  socialty1: require("../server/assets/socialties/socialty1.png"),
  socialty2: require("../server/assets/socialties/socialty2.png"),
  socialty3: require("../server/assets/socialties/socialty3.png"),
  socialty4: require("../server/assets/socialties/socialty4.png"),
  ratingspic1: require("../server/assets/ratings_items/ratings-pic-1.png"),
  ratingspic2: require("../server/assets/ratings_items/ratings-pic-2.png"),
  ratingspic3: require("../server/assets/ratings_items/ratings-pic-3.png"),
  ratingspic4: require("../server/assets/ratings_items/ratings-pic-4.png"),
  ratingsitem1: require("../server/assets/ratings_items/ratings-item-1.png"),
  ratingsitem2: require("../server/assets/ratings_items/ratings-item-2.png"),
  perkTraveling1: require("../server/assets/perks/traveling1.png"),
  perkTraveling2: require("../server/assets/perks/traveling2.png"),
  perkTraveling3: require("../server/assets/perks/traveling3.png"),
  perkTraveling4: require("../server/assets/perks/traveling4.png"),
  perkTraveling5: require("../server/assets/perks/traveling5.png"),
  perkTraveling6: require("../server/assets/perks/traveling6.png"),
  perkFashion1: require("../server/assets/perks/fashion1.png"),
  perkFashion2: require("../server/assets/perks/fashion2.png"),
  perkFashion3: require("../server/assets/perks/fashion3.png"),
  perkFashion4: require("../server/assets/perks/fashion4.png"),
  perkFashion5: require("../server/assets/perks/fashion5.png"),
  perkFashion6: require("../server/assets/perks/fashion6.png"),
  journal1: require("../server/assets/journals/journal1.png"),
  journal2: require("../server/assets/journals/journal2.png"),
  journal3: require("../server/assets/journals/journal3.png"),
  journal4: require("../server/assets/journals/journal4.png"),
  user1: require("../server/assets/users/user1.png"),
  user2: require("../server/assets/users/user2.png"),
  user3: require("../server/assets/users/user3.png")
}

export default images